version: '3.8'

services:
  rpc-monitor:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - CHAIN=Testnet
      - HYPERLIQUID_CHAIN_ID=998
      - HYPERLIQUID_TIMEOUT=10000
      - LOCAL_NODE_CHAIN_ID=998
      - LOCAL_NODE_TIMEOUT=5000
      - ARCHIVE_NODE_CHAIN_ID=998
      - ARCHIVE_NODE_TIMEOUT=10000
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
